trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: azure_fichas


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
    addToPath: true

- script: |
    echo "Creando virtualenv..."
    python -m venv .venv
    source .venv/bin/activate

    echo "Actualizando pip..."
    pip install --upgrade pip

    echo "Instalando dependencias..."
    pip install -r requirements.txt

    echo "Verificando variables de entorno..."
    echo "DATABASE_URL: $DATABASE_URL"
    echo "DATABASE_URL_ADMIN: $DATABASE_URL_ADMIN"
    echo "DATABASE_URL_PUBLICO: $DATABASE_URL_PUBLICO"
    echo "DATABASE_URL_LECTURA: $DATABASE_URL_LECTURA"

    echo "Ejecutando tests con pytest..."
    pytest --ds=fichas_backend.settings --disable-warnings -v
  displayName: 'Instalar dependencias y ejecutar tests'
  env:
    DATABASE_URL: $(DATABASE_URL)
    DATABASE_URL_ADMIN: $(DATABASE_URL_ADMIN)
    DATABASE_URL_PUBLICO: $(DATABASE_URL_PUBLICO)
    DATABASE_URL_LECTURA: $(DATABASE_URL_LECTURA)
    DJANGO_SETTINGS_MODULE: fichas_backend.settings



# Push a GitHub solo si las pruebas pasan
- script: |
    echo "Configurando GitHub remoto..."
    git remote remove origin-gh || true
    git remote add origin-gh https://Zarael25:$(GITHUB_TOKEN)@github.com/Zarael25/Backend.git
    git checkout develop
    git push origin-gh develop
  displayName: 'Push Azure develop to GitHub'