services:
  - type: web
    name: django-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate --noinput && gunicorn fichas_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
