# Generated by Django 5.2 on 2025-05-18 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('negocio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('en_revision', 'En Revisión'), ('verificado', 'Verificado'), ('rechazado', 'Rechazado'), ('oculto', 'Oculto')], default='en_revision', max_length=20)),
                ('categoria', models.CharField(choices=[('salud', 'Salud'), ('financiera', 'Financiera'), ('educacion', 'Educación'), ('tecnologia', 'Tecnología'), ('restaurantes', 'Restaurantes'), ('otros', 'Otros')], max_length=50)),
                ('doc_respaldo', models.BinaryField(null=True)),
                ('num_referencia', models.CharField(max_length=50, unique=True)),
                ('detalle', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('atencion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_tickets', models.IntegerField()),
                ('visible', models.BooleanField(default=True)),
                ('periodo_atencion', models.DurationField()),
                ('apertura', models.TimeField()),
                ('finalizacion', models.TimeField()),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='negocios.negocio')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_atencion', models.DateTimeField(blank=True, null=True)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='negocios.atencion')),
            ],
        ),
    ]
