# Generated by Django 4.2.3 on 2025-05-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='numero_ticket_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='posicion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atencion',
            name='periodo_atencion',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
