# Generated by Django 4.2.3 on 2025-05-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0002_atencion_numero_ticket_actual_ticket_posicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='posicion',
            field=models.IntegerField(default=0),
        ),
    ]
