# Generated by Django 4.2.3 on 2025-06-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0003_alter_ticket_posicion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atencion',
            new_name='FilaAtencion',
        ),
    ]
