# Generated by Django 4.2.3 on 2025-06-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0004_rename_atencion_filaatencion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filaatencion',
            old_name='atencion_id',
            new_name='fila_atencion_id',
        ),
    ]
