# Generated by Django 4.2.3 on 2025-06-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0005_rename_atencion_id_filaatencion_fila_atencion_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='atencion',
            new_name='fila_atencion',
        ),
    ]
