# Generated by Django 4.2.3 on 2025-06-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0006_rename_atencion_ticket_fila_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='filaatencion',
            name='permitir_cancelacion',
            field=models.BooleanField(default=False),
        ),
    ]
