# Generated by Django 4.2.3 on 2025-07-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0007_filaatencion_permitir_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='maximo_reservas_diarias',
            field=models.PositiveIntegerField(default=0, help_text='0 para ilimitado'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='permite_cancelar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negocio',
            name='tiempo_limite_cancelacion',
            field=models.PositiveIntegerField(default=60, help_text='Tiempo en minutos'),
        ),
    ]
