# Generated by Django 4.2.3 on 2025-07-07 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0008_negocio_maximo_reservas_diarias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filaatencion',
            name='permitir_cancelacion',
        ),
    ]
