# Generated by Django 4.2.3 on 2025-07-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0011_reservadiariausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='doc_respaldo',
            field=models.FileField(blank=True, null=True, upload_to='docs_respaldo/'),
        ),
    ]
