"""
Django settings for fichas_backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config
import dj_database_url
import os
import sys


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gaabe4*q8e&hs%rji7(gi)w&)7%+h#%#fg=r6pq%r7lpfzimrp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True





# Lista de hosts permitidos para que el servidor Django acepte peticiones.
# Esto evita errores de seguridad (DisallowedHost) cuando la aplicación recibe
# solicitudes desde diferentes dominios o direcciones IP.

ALLOWED_HOSTS = [
    'localhost',                         # Desarrollo local
    '127.0.0.1',                         # Loopback local
    '10.0.2.2',                          # IP usada por emuladores Android
    '192.168.1.101',                     # Dirección IP dentro de la red local (cambiar según el entorno)
    'backend-fichasvirtuales.onrender.com', # Dominio del backend desplegado en Render
    'filas-backend.onrender.com',        # Alias o dominio adicional del backend en Render
]



#LOGGING = {
#    "version": 1,
#    "disable_existing_loggers": False,
#    "handlers": {
#        "console": {
#            "class": "logging.StreamHandler",
#        },
#    },
#    "root": {
#        "handlers": ["console"],
#        "level": "DEBUG",
#    },
#}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": "logs/django_errors.log",
            "formatter": "verbose",
        },
    },
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": "WARNING",  # WARNING para capturar 404, ERROR para 500
            "propagate": False,
        },
    },
}




# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'usuarios',
    'negocios',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',


    "usuarios.middleware.RequestMiddleware",


    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',

    
]

ROOT_URLCONF = 'fichas_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fichas_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



# Configuración de las bases de datos en Django.
# Se utilizan variables de entorno para mayor seguridad y flexibilidad,
# gestionadas mediante dj_database_url y decouple (config).


DATABASES = {
    # Base de datos principal usada por defecto en la aplicación.
    'default': dj_database_url.config(default=config('DATABASE_URL')),

    # Base de datos destinada operaciones administrativas
    # (posiblemente con mayores privilegios).
    'admin': dj_database_url.config(default=config('DATABASE_URL_ADMIN')),

    # Base de datos para consultas públicas.
    'publico': dj_database_url.config(default=config('DATABASE_URL_PUBLICO')),

    # Base de datos en modo solo lectura.
    'lectura': dj_database_url.config(default=config('DATABASE_URL_LECTURA')),

    # ----------- CONFIGURACIÓN LOCAL ------------------
    # Ejemplo de conexión manual a PostgreSQL para desarrollo local.
    # Se comenta porque en producción se usan las variables de entorno.
    #
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',  # Motor de base de datos
    #     'NAME': config('DB_NAME'),                  # Nombre de la base de datos
    #     'USER': config('DB_USER'),                  # Usuario de la base de datos
    #     'PASSWORD': config('DB_PASSWORD'),          # Contraseña del usuario
    #     'HOST': config('DB_HOST'),                  # Dirección del servidor
    #     'PORT': config('DB_PORT'),                  # Puerto de conexión
    # }
}




# Definición de los "Database Routers" en Django.
# Los routers permiten controlar a qué base de datos van las operaciones
# (lecturas/escrituras) dependiendo del modelo o la lógica definida.

DATABASE_ROUTERS = ["usuarios.db_router.SafeRoleBasedRouter"]  # Router personalizado para manejar roles y permisos.

# Para pruebas unitarias:
# Se desactiva el uso de routers porque pueden generar conflictos de permisos.
# Al dejarlo como lista vacía, todas las operaciones usarán la DB por defecto.
# DATABASE_ROUTERS = []



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Carpeta donde se recopilan archivos estáticos para producción

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'









# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#REST_FRAMEWORK = {
#    'DEFAULT_AUTHENTICATION_CLASSES': (
#        'rest_framework_simplejwt.authentication.JWTAuthentication',
#    ),
#}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # ahora todos requieren token
    )
}




# Configuración de Simple JWT para la autenticación basada en tokens.
# Define tiempos de vida, rotación de tokens y mapeo de claims en el JWT.

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=20),  # Duración del token de acceso (20 min)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Duración del token de refresco (7 días)
    'ROTATE_REFRESH_TOKENS': False,                  # Si True: genera un nuevo refresh token al usarlo
    'BLACKLIST_AFTER_ROTATION': False,               # Si True: el refresh token antiguo se invalida al rotar
    'UPDATE_LAST_LOGIN': True,                       # Actualiza el campo "last_login" del usuario al autenticarse

    # Personalización de identificadores del usuario en el JWT
    'USER_ID_FIELD': 'usuario_id',  # Campo real de la PK en tu modelo de usuario
    'USER_ID_CLAIM': 'user_id',     # Nombre del claim que aparecerá en el JWT
}


# Modelo de usuario personalizado definido en la app "usuarios".
# Esto reemplaza el modelo de usuario por defecto de Django.
AUTH_USER_MODEL = 'usuarios.Usuario'

# Configuración de CORS (Cross-Origin Resource Sharing).
# Con True se permiten peticiones desde cualquier origen.
CORS_ALLOW_ALL_ORIGINS = True

# Configuración de archivos multimedia (imágenes, documentos, etc.)
MEDIA_URL = '/media/'                # URL base para acceder a los archivos
MEDIA_ROOT = BASE_DIR / 'media'      # Carpeta en el servidor donde se guardan