# Generated by Django 5.2 on 2025-05-18 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioticket',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='negocios.ticket'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usuarioticket',
            unique_together={('usuario', 'ticket')},
        ),
    ]
