# Generated by Django 4.2.3 on 2025-06-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarioticket_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='suspendido_contador',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='suspendido_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
