# Generated by Django 4.2.3 on 2025-06-15 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_suspendido_contador_usuario_suspendido_hasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_accion', models.CharField(max_length=100)),
                ('ruta_acceso', models.CharField(max_length=255)),
                ('origen_conexion', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
